
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='pipen-report',
    version='0.0.1',
    description='Report generation system for pipen.',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/pwwang/pipen-report", "repository": "https://github.com/pwwang/pipen-report"},
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"pipen": ["report = pipen_report:PipenReportPlugin"]},
    packages=['pipen_report'],
    package_dir={"": "."},
    package_data={},
    install_requires=['liquidpy', 'pipen', 'python-slugify==4.*'],
)
