name: Build and Deploy

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: "3.12"
          enable-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: |
          uv sync
      - name: Install frontend dependencies
        run: |
          uv run pipen report update
      - name: Build and test
        run: |
          uv run pytest tests/ --junitxml=junit/test-results.xml

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Build and publish
        run: |
          uv build
          uv publish -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
        if: success()
