name: Build Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install ghp-import
          poetry config virtualenvs.create false
          poetry install -v
      - name: Update docs
        run: |
          python -m pip install -r docs/requirements.txt
          cd docs
          cp ../README.md index.md
          sed -i 's#docs/logo.png#logo.png#g' index.md
          cd ..
          mkdocs build --clean
          cp -r example/ site/
      - name: ghp-import
        run: |
          # mkdocs gh-deploy --force
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ghp-import -m "GitHub Action deploy (${GITHUB_SHA:0:7})" -f -p site/
        if: success()
