name: Build Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install ghp-import
          poetry config virtualenvs.create false
          # poetry install -v
      - name: Update docs
        run: |
          python -m pip install mkdocs
          python -m pip install -r docs/requirements.txt
          cd docs
          cp ../README.md index.md
          sed -i 's#docs/logo.png/#logo.png#g' index.md
          cd ..
          mkdocs build --clean
          cp -r example/ site/
      - name: ghp-import
        run: |
          # mkdocs gh-deploy --force
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ghp-import -m "GitHub Action deploy (${GITHUB_SHA:0:7})" -f -p site/
        if: success()

  fix-index:
    needs: docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Fix index.html
        run: |
          echo ':: head of index.html - before ::'
          head index.html
          sed -i '1,5{/^$/d}' index.html
          echo ':: head of index.html - after ::'
          head index.html
        if: success()
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
        if: success()
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
        if: success()
